trigger:
  - main

pool:
  name: Self-Hosted # Make sure this matches the name of your self-hosted agent pool

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x" # Adjust to your preferred Python version
      addToPath: true

  - script: |
      echo "Running on agent: $AGENT_NAME"
      python3 --version
    displayName: "Debug Agent Info"

  - script: |
      python3 -m pip install --upgrade pip
      pip install okareo
    displayName: "Install Okareo Python Package"

  - script: |
      python3 example.py
    env:
      OKAREO_API_KEY: $(OKAREO_API_KEY)
      OPENAI_API_KEY: $(OPENAI_API_KEY)
    displayName: "Run example.py script"
