# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Self-Hosted

steps:
  - script: |
      export OKAREO_API_KEY=$(OKAREO_API_KEY)
    displayName: "Setup API Keys"

  - script: |
      curl -O -L https://github.com/okareo-ai/okareo-cli/releases/latest/download/okareo_darwin_arm64.tar.gz
      tar -xvf okareo_darwin_arm64.tar.gz
      chmod 777 okareo
    displayName: "Install Okareo CLI"

  - script: |
      ./okareo init -l ts
      ls -al
      ./okareo run -f example
    displayName: "Run Okareo Example"
